version: "3.7"
services:
    www:
        build: .
        ports: 
            - "3000:80"
        volumes:
            - ./conf/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mariadb:10.3.18
        ports: 
            - "3306:3306"
        command: [
            '--default-authentication-plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: root 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 3001:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: root
            UPLOAD_LIMIT: 128M
volumes:
    persistent:
